# Generated by Django 3.0.7 on 2020-06-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_solicitacao_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='executada',
            field=models.BooleanField(default=False),
        ),
    ]
