# Generated by Django 3.0.7 on 2020-06-27 13:15

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_solicitacao_executada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='validade',
            field=creditcards.models.CardExpiryField(verbose_name='expiration date'),
        ),
    ]
