# Generated by Django 3.0.7 on 2020-06-27 13:47

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0004_auto_20200627_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='foto_cpf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='foto_identidade',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='validade',
            field=creditcards.models.CardExpiryField(verbose_name='Data de expiração'),
        ),
    ]
