# Generated by Django 3.0.7 on 2020-06-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_auto_20200627_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='comprovante_verso',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
